In [1]:
import re
import unicodedata

In [13]:
s = "1234abcd"

In [16]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
a = torch.tensor([[1,2,3,4]],dtype=torch.float32)
aa = torch.tensor([[5,6,7,8]])
b = F.softmax(a[0])
b = torch.nn.LogSoftmax()
a = torch.randn((2,3))
print (a.shape[0])
embedding = nn.Embedding(4920, 256)
input = torch.LongTensor([[1]])
output = embedding(input)
print (output.size())

2
torch.Size([1, 1, 256])


/home/song/.local/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  import sys


In [1]:
# %load globalSetting.py
from __future__ import unicode_literals, print_function, division

import sys
import os
import glob
import time
import math
import random

from io import open
import unicodedata
import re

import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F
import numpy as np

#import matplotlib.pyplot as plt
#plt.switch_backend('agg')
#import matplotlib.ticker as ticker

SOSToken = 0
EOSToken = 1
MAXLEN = 10
engPrefix = ("i am", "i m", "he is", "he s", "she is", "she s","you are",
          "you re", "we are", "we re","they are", "they re")
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")


if (__name__=="__main__"):
    print("gobalSetting begins")
    print (device)

if (__name__!="__main__"):
    print ("Module: globalSetting loaded")


gobalSetting begins
cuda


In [19]:
dropoutLayer = nn.Dropout(1
                         )

In [20]:
a = torch.tensor((list(range(10))),dtype=torch.float)
print (a)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [21]:
da = dropoutLayer(a)
print (da)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])


In [5]:
m = nn.Dropout(p=0.2)
input = torch.randn(20)
output = m(input)

In [6]:
print (input)

tensor([ 1.4227, -0.9663, -1.0891, -0.7649,  0.9584,  1.7892,  1.2121,  0.6661,
        -0.1005,  0.3915, -2.4224,  0.0437, -1.3642,  1.1668,  0.1201, -0.8955,
         0.6754,  0.2815,  1.5088, -0.9859])
